changes to python script updated

diff --git a/.github/workflows/otta.yml b/.github/workflows/otta.yml
--- a/.github/workflows/otta.yml
+++ b/.github/workflows/otta.yml
@@ -5,36 +5,36 @@ on:
   workflow_dispatch:
   schedule:
     - cron: '0 */4 * * *'
+
 jobs:
   scrape:
     runs-on: ubuntu-latest
     steps:
-      - name: Checking out repo
-        uses: actions/checkout@v3
-      - name: Setting up Python
-        uses: actions/setup-python@v4
+      - name: Check out this repo
+        uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
         with:
           python-version: '3.9'
-      - name: Installing package list
-        run: apt list --installed    
-      - name: Removing previous chrome instances on runner 
-        run: sudo apt purge google-chrome-stable  
-        
-       # Need to fetch reqs if needed
-      - name: Installing all necessary packages
-        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
-      - name: Install xvfb
-        run: sudo apt-get install xvfb
+      - name: Installed package list
+        run: apt list --installed
+      - name: Remove Chrome
+        run: sudo apt purge google-chrome-stable
+      - name: Remove default Chromium
+        run: sudo apt purge chromium-browser
+      - name: Install a new Chromium
+        run: sudo apt install -y chromium-browser
       - name: Install all necessary packages
         run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
-      - name: Run the scraping script
-        run: python scratchpad.py
-      - name: Parse UniqueJobsdataMasterFile.json into table
+      - name: Run the script
+        run: |
+          python scratchpad.py || echo "Script execution failed, but continuing workflow..."
+      - name: Parse ottacomdata.json into table
         id: parse-json
         run: |
           echo "| Job Title | Job Location | Job Link | Job Posted |" > README.md
           echo "| --- | --- | --- | --- |" >> README.md
-          jq -r '.[] | "| " + .job_title + " | " + .job_location + " | " + "[Apply](" + .JobLink + ")" + " | " + "$(date +'%e %B %Y')" + " |"' UniqueJobsdataMasterFile.json >> README.md
+          jq -r '.[] | "| " + .job_title + " | " + .job_location + " | " + "[Apply](" + .JobLink + ")" + " | " + "$(date +'%e %B %Y')" + " |"' ottacomdata.json >> README.md
       - name: Commit and push if it changed
         run: |
           git config user.name "Automated"
