Updated workflow file

diff --git a/.github/workflows/zfeu.yml b/.github/workflows/zfeu.yml
--- a/.github/workflows/zfeu.yml
+++ b/.github/workflows/zfeu.yml
@@ -24,7 +24,7 @@ jobs:
           pip install requests beautifulsoup4 pandas webdriver-manager selenium
 
       - name: Run the scraping script
-        run: python scratchpad.py || echo "Script failed, continuing workflow"
+        run: python scrape_latest_jobs.py || echo "Script failed, continuing workflow"
 
       - name: Parse ottacomdata.json into table
         id: parse-json
@@ -38,17 +38,7 @@ jobs:
           git config --global user.name "Suresh Parimi"
           git config --global user.email "reachparimi@gmail.com"
 
-      - name: Pull changes from remote repository
-        run: git pull
-
-      - name: Commit and push if it changed
-        run: |
-          git add README.md
-          timestamp=$(date -u)
-          git commit -m "Latest jobs: ${timestamp}" || exit 0
-          git push
-
-  job1:
+  scrape:
     runs-on: ubuntu-latest
 
     steps:
@@ -79,18 +69,8 @@ jobs:
           git config --global user.name "Your Name"
           git config --global user.email "your-email@example.com"
 
-      - name: Pull changes from remote repository
-        run: git pull
-
-      - name: Commit and push if it changed
-        run: |
-          git add README.md
-          timestamp=$(date -u)
-          git commit -m "Latest jobs: ${timestamp}" || exit 0
-          git push
-
   combine-data:
-    needs: [job2, job1]
+    needs: [job2, scrape]
 
     runs-on: ubuntu-latest
 
@@ -115,13 +95,17 @@ jobs:
       - name: Update README.md from alljobs.json
         id: update-readme
         run: |
-          echo "# Latest Jobs" > README.md
-          echo "" >> README.md
-          echo "This page is updated at $(TZ='Europe/Paris' date +'%B %d, %Y %H:%M:%S')" >> README.md
-          echo "" >> README.md
-          echo "| Job Title | Job Location | Job Link | Job Posted | Visa Sponsorship |" >> README.md
-          echo "| --- | --- | --- | --- | --- |" >> README.md
-          jq -r '.[] | "| \(.position) | \(.location) | [Apply](\(.description)) | \(.post_date) | \(.visa) |"' alljobs.json >> README.md || echo "JSON parsing failed"
+          git pull origin main
+          cat README.md >> new_README.md
+          echo "" >> new_README.md
+          echo "# Latest Jobs" >> new_README.md
+          echo "" >> new_README.md
+          echo "This page is updated at $(TZ='Europe/Paris' date +'%B %d, %Y %H:%M:%S')" >> new_README.md
+          echo "" >> new_README.md
+          echo "| Job Title | Job Location | Job Link | Job Posted | Visa Sponsorship |" >> new_README.md
+          echo "| --- | --- | --- | --- | --- |" >> new_README.md
+          jq -r '.[] | "| \(.position) | \(.location) | [Apply](\(.description)) | \(.post_date) | \(.visa) |"' alljobs.json >> new_README.md || echo "JSON parsing failed"
+          mv new_README.md README.md
 
       - name: Set Git user credentials
         run: |
