jobnames and timezone changed

diff --git a/.github/workflows/zfeu.yml b/.github/workflows/zfeu.yml
--- a/.github/workflows/zfeu.yml
+++ b/.github/workflows/zfeu.yml
@@ -7,7 +7,7 @@ on:
     - cron: '0 */4 * * *'
 
 jobs:
-  job2:
+  ottacom:
     runs-on: ubuntu-latest
 
     steps:
@@ -24,7 +24,7 @@ jobs:
           pip install requests beautifulsoup4 pandas webdriver-manager selenium
 
       - name: Run the scraping script
-        run: python scrape_latest_jobs.py || echo "Script failed, continuing workflow"
+        run: python scratchpad.py || echo "Script failed, continuing workflow"
 
       - name: Parse ottacomdata.json into table
         id: parse-json
@@ -38,7 +38,7 @@ jobs:
           git config --global user.name "Suresh Parimi"
           git config --global user.email "reachparimi@gmail.com"
 
-  scrape:
+  relocatewithus:
     runs-on: ubuntu-latest
 
     steps:
@@ -70,7 +70,7 @@ jobs:
           git config --global user.email "your-email@example.com"
 
   combine-data:
-    needs: [job2, scrape]
+    needs: [ottacom, relocatewithus]
 
     runs-on: ubuntu-latest
 
@@ -100,7 +100,7 @@ jobs:
           echo "" >> new_README.md
           echo "# Latest Jobs" >> new_README.md
           echo "" >> new_README.md
-          echo "This page is updated at $(TZ='Europe/Paris' date +'%B %d, %Y %H:%M:%S')" >> new_README.md
+          echo "This page is updated at $(TZ='Asia/Kolkata' date +'%B %d, %Y %H:%M:%S')" >> new_README.md
           echo "" >> new_README.md
           echo "| Job Title | Job Location | Job Link | Job Posted | Visa Sponsorship |" >> new_README.md
           echo "| --- | --- | --- | --- | --- |" >> new_README.md
